apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 5000
      nodePort: 30390
      protocol: TCP
      targetPort: 5000